apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true  # High risk configuration
      readOnlyRootFilesystem: false
