name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      with:
        format: sarif
        outputFile: results.sarif
        files: "."  # Scan entire repository << Critical fix
        verbose: true

    - name: Debug SARIF Contents
      run: |
        if [ -f results.sarif ]; then
          cat results.sarif
        else
          echo "No SARIF file generated"
        fi
        
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
