name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v3

    - name: Install git
      run: sudo apt-get install -y git
      
    - uses: kubescape/github-action@v3.0.21
      with:
        format: sarif
        outputFile: results.sarif
        files: "." 
        verbose: true
        severityThreshold: critical
        
    - name: List repository files
      run: ls -laR

    - name: Debug SARIF Contents
      run: |
        if [ -f results.sarif ]; then
          cat results.sarif
        else
          echo "No SARIF file generated"
        fi
        
    - name: Scan with Kubescape CLI
      run: |
        curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh \
          /bin/bash \
          ~/.kubescape/bin/kubescape scan . \
          --format sarif \
          --output results.sarif 
          
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
